#eureka:
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:8881/dev/
server:
    port: 6661
#spring:
#  application:
#    name: service-feign


spring:
    application:
        name: service-feign
    cloud:
      config:
        profile: dev
        discovery:
          enabled: true
          service-id: ${config.service.id}
#          service-id: ${config.service.id}}
        name: ${spring.application.name},config-center
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest