#eureka:
#    client:
#        serviceUrl:
#            defaultZone: ${dev.server.defaultZone}
server:
    port: ${server.port}
spring:
    application:
        name: pipeline-service
    cloud:
      config:
        profile: dev
        discovery:
          enabled: true
          service-id: ${config.service.id}
        name: ${spring.application.name},config-center
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
    redis:
     cluster:
      nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
management:
  security:
    enabled: false


#        uri: http://localhost:8888/
